CREATE USER IF NOT EXISTS 'associationAPEAJ'@'localhost' IDENTIFIED BY '1234Apeaj';
CREATE DATABASE IF NOT EXISTS apeaj
CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
GRANT ALL PRIVILEGES ON apeaj .* TO 'associationAPEAJ'@'localhost';
FLUSH PRIVILEGES;

